# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81198ea8045ab2da08d297aa5817aa1e4d841d9b7c80fe53cb70128f7e7e7abe5f76e23b55ce69b42f564db0984fe2e277bc5d6a76d1380ce07254ec91b7003b

test:
  secret_key_base: 647990400a2f4d7c0b8e27c5e025a04d772ec9bd71b376414f2cfa3d4877053cfa3f076672ff763543d1c1cebfe3f21b41b68bdc44d60efe21b3776ddfbfc95e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
